# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "xxxxdev"
  config.vm.network "private_network", ip: "192.168.88.10"
  config.vm.boot_timeout = 300
  #config.vm.synced_folder "../../../", "/tiki/www", :mount_options => ["dmode=777", "fmode=777"], create: true
  config.vm.synced_folder "../../../", "/travel/xxxx", :nfs => { :mount_options => ["dmode=777","fmode=666"] }
  #config.vm.synced_folder "../../../", "/travel/xxxx", type:"smb"
  config.vm.provider :virtualbox do |v|
    v.name = "xxxxdev"
    v.memory = 512
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../provision/web.yml"
    ansible.sudo = true
  end
end
