# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "tikelk"
  config.vm.network "private_network", ip: "192.168.88.11"
  config.vm.synced_folder "../../../", "/tiki/www/tala", disabled: true
  
  config.vm.provider :virtualbox do |v|
    v.name = "tikielk"
    v.memory = 512
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../provision/elk.yml"
    ansible.sudo = true
  end
end	
